apiVersion: v1
kind: ConfigMap
metadata:
  name: isl-config
  namespace: isl-detection
data:
  FLASK_ENV: "production"
  MODEL_PATH: "/app/models/dynamic.tflite"
  LANDMARK_MODEL_PATH: "/app/models/landmark_model.h5"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  WANDB_PROJECT: "isl-detection"
  WANDB_MODE: "online"
  LOG_LEVEL: "INFO"
