apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: isl-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: managed-csi
